apiVersion: cache.platform.ohanyere.io/v1alpha1
kind: RedisClaim
metadata:
  name: checkout-api-redis
  labels:
    app.kubernetes.io/name: checkout-api
    finops.ohanyere.io/cost-center: platform-engineering
spec:
  environment: dev
  size: small
  evictionPolicy: allkeys-lru
